const NAME_OR_PASSWORD_IS_NOT_REQUIRED = 'name_or_password_is_not_required';
const USER_ALREADY_EXISTS = 'user_already_exists';
const USER_DOES_NOT_EXISTS = 'user_does_not_exists';
const PASSWORD_IS_INCORRENT = 'password_is_incorrent';
const UNAUTHORIZATION = 'unauthorization';
const UNPERMISSION = 'unpermission';
const ADD_COLLECT_MOMENT_FAIL = 'ADD_COLLECT_MOMENT_FAIL';
const ADD_COLLECT_COMMENT_FAIL = 'ADD_COLLECT_COMMENT_FAIL';
const CREATE_MOMENT_FAIL = 'CREATE_MOMENT_FAIL';
const GET_MOMENT_FAIL = 'GET_MOMENT_FAIL';
const GET_MOMENT_LIST_ALL = 'GET_MOMENT_LIST_ALL';
const GET_MOMENT_LIST_HOT = 'GET_MOMENT_LIST_HOT';
const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';
const GET_BANNER_LIST_FAIL = 'GET_BANNER_LIST_FAIL';
const UPLOAD_PICTURE_FAIL = 'UPLOAD_PICTURE_FAIL';
const UPLOAD_AVATAR_FAIL = 'UPLOAD_AVATAR_FAIL';
const GET_PICTURE_FAIL = 'GET_PICTURE_FAIL';
const GET_MY_MOMENT_LIST = 'GET_MY_MOMENT_LIST';
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

module.exports = {
  NAME_OR_PASSWORD_IS_NOT_REQUIRED,
  USER_ALREADY_EXISTS,
  USER_DOES_NOT_EXISTS,
  PASSWORD_IS_INCORRENT,
  UNAUTHORIZATION,
  UNPERMISSION,
  ADD_COLLECT_MOMENT_FAIL,
  ADD_COLLECT_COMMENT_FAIL,
  CREATE_MOMENT_FAIL,
  GET_MOMENT_FAIL,
  GET_MOMENT_LIST_ALL,
  GET_MOMENT_LIST_HOT,
  CREATE_COMMENT_FAIL,
  GET_BANNER_LIST_FAIL,
  UPLOAD_PICTURE_FAIL,
  UPLOAD_AVATAR_FAIL,
  GET_PICTURE_FAIL,
  GET_MY_MOMENT_LIST,
  UPDATE_USER_INFO
}

